version: '3'

networks:
  laravel-net:
    driver: bridge
    name: ${APP_NAME}-net
    
    
services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: ${APP_NAME}-app
    working_dir: /var/www/
    tty: true
    networks:
      - ${APP_NAME}-net
    volumes:
      - ./laravel:/var/www/html:delegated
    ports:
      - ${APP_PORT}:80

  redis:
    image: redis:alpine
    container_name: ${APP_NAME}-redis
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - ${APP_NAME}-net
    volumes:
      - ./data/redis:/data

  mariadb:
    image: mariadb/server:10.3
    container_name: ${APP_NAME}-mariadb
    restart: unless-stopped
    tty: true
    ports:
      - ${DB_PORT}:3306
    networks:
      - ${APP_NAME}-net
    environment:
      MARIADB_DATABASE: homestead
      MARIADB_USER: homestead
      MARIADB_PASSWORD: secret
      MARIADB_ROOT_PASSWORD: secret
    volumes:
      - ./data/mariadb:/var/lib/mysql
      
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: ${APP_NAME}-phpmyadmin
    restart: always
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_HOST: mariadb
      PMA_ARBITRARY: 1
      PMA_USER: root
      PMA_PORT: 3306
      PMA_PASSWORD: secret
    networks:
      - ${APP_NAME}-net